#!/bin/bash

# A tool for segregating files to it's specified folder

usage(){
	cat << EOF
	 USAGE
	     ./segregate [-h|-w|] [dir]
		-w 	  : Warn on duplicates 
		-d [dir]  : directory to perform the segregation ( defaults to CWD )
		-h 	  : Usage section of the command
EOF
}

segregator(){
	dir="$1"
	touch "$dir"/.dirfile
	ls -d $dir/*/ > "$dir"/.dirfile
	# moved dir to .dirfile
	find "$dir" -maxdepth 1 -type f -nowarn > "$dir"/.allfiles
	# moved files to .allfiles

}

override(){
}
while getopts ":hd:o" OPTS; do
	case "$OPTS" in
		d)
			dir=${OPTARG}
			if [[ -d $dir ]]; then 
				echo "Performing Segregation in directory $dir"
				segregator $dir
			else
				echo "Is not a directory"
				exit 1
			fi
			;;
		h)
			usage
			;;
		\?)
			echo "Invalid option"
			exit 1
			;;
		:)
			echo "Missing Argument"
			exit 1
			;;
	esac
done


if [[ ! -n $1 ]]; then
	usage
fi	

shift $((OPTIND-1))

if [[ $# -ge 1 ]]; then
	echo "Too Many arguments."
	exit 1
	usage
fi
