#!/bin/bash

# A tool for segregating files to it's specified folder

usage(){
	cat << EOF
	 USAGE
	     ./segregate [-h|-w|] [dir]
		-w 	  : Warn on duplicates 
		-d [dir]  : directory to perform the segregation ( defaults to CWD )
		-h 	  : Usage section of the command
EOF
}

fileExtensionStripper(){
	line="$1"
	if [[ ! -n $( ls -ld $dir/Miscellaneous 2>/dev/null) ]]; then
		mkdir -p $dir/Miscellaneous
	fi
			
	while read -r line || [[ -n $line ]]; do
		if [[ -n "$line" ]]; then
			file=$(echo $line | rev | cut -d '/' -f 1 | rev | grep -Eiv '\.' ) 
			extFile=$(echo $line | rev | cut -d '/' -f 1 | rev | grep -Ei '\.')
		    #   	echo $extFile | sed -r "/^$/d" | grep -Eiv '^\.' 
		 echo "$extFile" | sed '/^$/d' | grep -Eiv '^\.' | grep -Ei '\.[a-z]{1,20}$' | while read -r file; do
		       
  		ext="${file##*.}"
  		upper_ext="${ext^^}" 
  		base="${file%.*}"
  		mkdir -p "$dir/$upper_ext" 2>/dev/null
  		mv "$dir/$file" "$dir/$upper_ext/" 2>/dev/null
		done

		echo $file | sed -r "/^$/d" | sed -r "s|.*|$dir/&|" | xargs -n 1 -I {} mv ./{} $dir/Miscellaneous/ 2>/dev/null
		fi | sed -r '/^$/d' 
	done <  "$line"
        
}

segregator(){
	dir="$1"
	touch "$dir"/.dirfile
	ls -d $dir/*/ > "$dir"/.dirfile
	find "$dir" -maxdepth 1 -type f -nowarn > "$dir"/.allfiles
	while read -r line && [[ -n $line ]]; do
		fileExtensionStripper "$line"
	done < $dir/.allfiles
	
	
}


while getopts ":hd:o" OPTS; do
	case "$OPTS" in
		o) 
			override="y"
			;;
		d)
			dirPresent="y"
			dir=${OPTARG}
			;;
		h)
			usage
			;;
		\?)
			echo "Invalid option"
			exit 1
			;;
		:)
			echo "Missing Argument"
			exit 1
			;;
	esac
done

if [[ $override == "y" ]] && [[ $dirPresent == "y" ]]; then 
				if [[ -d $dir ]]; then 
				echo "Performing Segregation in directory $dir"
				segregator $dir
			else
				echo "Is not a directory"
				exit 1
			fi
			
echo "overriding warning and options"
fi

if [[ ! -n $1 ]]; then
	usage
fi	

shift $((OPTIND-1))

if [[ $# -ge 1 ]]; then
	echo "Too Many arguments."
	exit 1
	usage
fi

